### ISSUE TITLE
Segmentation fault when running the node in ROS

### ISSUE THREAD

**Issue by TheRobotStudio** [fmina/ros_picoflexx#6]
Hi, I had an issue when running this code, which I solved with a workaround, but there might be a better solution. I posted that on rosanswer : http://answers.ros.org/question/219817/getting-the-picoflexx-depth-sensor-working-on-ros-solved/

**Comment by fmina** [comment]
Hi, 
I think this happened because you have to set the correct camera ID in the parameter file. Now I am displaying the detected camera(s) ID and you have to copy it into the parameters file once to associate it with a camera name.

Please let me know if this fixes the problem.

**Comment by TheRobotStudio** [comment]
Hi, Great, it works, I just had to fix a few errors, one ';' missing in header file, one ':' missing in source code file, and had to change the name 'cam_id' to 'camera_id' in the yaml parameter file to fit the name used in the cc file. 
Thanks for sharing!
